[package]
name = "presence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-presence = "1.2"
dotenv = "0.15.0"
sysinfo = "0.30.11"
